blank_issues_enabled: false
contact_links:
  - name: Security problem
    url: https://github.com/lupanostefano/Gravitone/security/advisories/new
    about: Report vulnerabilities privately, please.
  - name: Support the project
    url: https://ko-fi.com/hikari22
    about: Buy the developer a coffee on Ko-fi.
